name: fluttercrud
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  sembast
  sembast: ^2.4.3

  path_provider: ^1.6.7

  #  ------
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  #  ------
  image_picker: ^0.6.5+3
  #  ------
  persian_datepicker: ^1.3.1

  cupertino_icons: ^0.1.3

  url_launcher: ^5.4.5

  maps_launcher: ^1.2.0

  flutter_localizations:
    sdk: flutter
  flutter_translate: ^1.6.0
  flutter_translate_annotations: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #
  flutter_translate_gen: ^1.2.3
  build_runner: ^1.7.0

  get_it: ^3.1.0

flutter:


  uses-material-design: true

  #  ------
  assets:
    - assets/images/empty-avatar.jpg
    - assets/i18n/

  fonts:
    - family: Shabnam-FD
      fonts:
        - asset: assets/fonts/Shabnam-FD.ttf

